/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\ancient_chinese_sword.glb -T --types 
Files: .\ancient_chinese_sword.glb [5.41MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\ancient_chinese_sword-transformed.glb [847.26KB] (84%)
Author: Johanes Chendra (https://sketchfab.com/venombite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ancient-chinese-sword-acd5ac4cca104805a5afa43c43480dec
Title: Ancient Chinese Sword
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    Scabbard_Scabbard_0: THREE.Mesh
    Sword_Sword_0: THREE.Mesh
  }
  materials: {
    Scabbard: THREE.MeshStandardMaterial
    Sword: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function AncientChineseSword(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ancient_chinese_sword-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Scabbard_Scabbard_0.geometry} material={materials.Scabbard} position={[-0.158, 0.036, 0.068]} rotation={[-0.572, -1.128, -2.784]} />
      <mesh geometry={nodes.Sword_Sword_0.geometry} material={materials.Sword} position={[-0.089, 0.13, -0.023]} rotation={[-1.16, -0.744, 2.961]} />
    </group>
  )
}

useGLTF.preload('/models/ancient_chinese_sword-transformed.glb')
