/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\chinese_sword_dao_of_qing_dynasty.glb -T --types 
Files: .\chinese_sword_dao_of_qing_dynasty.glb [10.29MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\chinese_sword_dao_of_qing_dynasty-transformed.glb [1.03MB] (90%)
Author: leeeck (https://sketchfab.com/leeeck)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinese-sword-dao-of-qing-dynasty-34739e194ac246dc84b736f04f8a567b
Title: Chinese Sword Dao of Qing Dynasty
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type {GLTF} from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    blade: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    steel: THREE.MeshStandardMaterial
    wood: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chinese_sword_dao_of_qing_dynasty-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blade} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.steel} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.wood} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/chinese_sword_dao_of_qing_dynasty-transformed.glb')
