/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\chinese_sword_-_han_jian.glb -T --types 
Files: .\chinese_sword_-_han_jian.glb [41.42MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\chinese_sword_-_han_jian-transformed.glb [548.75KB] (99%)
Author: ShaoChiChen (https://sketchfab.com/Brandon..Chen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinese-sword-han-jian-ebd48df035c548b2ba18b3c4c499fa57
Title: Chinese Sword - Han Jian
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    Sword_Sword_0: THREE.Mesh
  }
  materials: {
    Sword: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function ChineseSwordHanJian(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chinese_sword_-_han_jian-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sword_Sword_0.geometry} material={materials.Sword} position={[-8.398, 0, 43.592]} rotation={[Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/chinese_sword_-_han_jian-transformed.glb')
