/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\chinese_hand_fan.glb -T --types 
Files: .\chinese_hand_fan.glb [2.38MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\chinese_hand_fan-transformed.glb [290.44KB] (88%)
Author: Alex Sanches (https://sketchfab.com/ASanches)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chinese-hand-fan-735311cf14d544b1adbd61d7d8d6232e
Title: Chinese Hand Fan
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type {GLTF } from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    Day7_ChineseFan__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chinese_hand_fan-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Day7_ChineseFan__0.geometry} material={materials['Scene_-_Root']} position={[0, -0.067, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/chinese_hand_fan-transformed.glb')
