/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\jian_styled_sword.glb -T --types 
Files: .\jian_styled_sword.glb [10.59MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\jian_styled_sword-transformed.glb [595.44KB] (94%)
Author: iceboxX708 (https://sketchfab.com/iceboxX708)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jian-styled-sword-391ab2cbf3024f1fb09f14832234d675
Title: Jian Styled Sword
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type {GLTF } from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Sword_Sharp_SG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/jian_styled_sword-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Sword_Sharp_SG} rotation={[-0.482, 0.053, 0.084]} scale={3.456} />
    </group>
  )
}

useGLTF.preload('/models/jian_styled_sword-transformed.glb')
