/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\old_the_wagasa__japanese_umbrella.glb -T --types 
Files: .\old_the_wagasa__japanese_umbrella.glb [15.55MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\old_the_wagasa__japanese_umbrella-transformed.glb [676.47KB] (96%)
Author: shadowdarkdemon2 (https://sketchfab.com/shadowdarkdemon2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-3d-old-the-wagasa-japanese-umbrella-v3-23028b4a1e90409db025867565b51569
Title: [FREE] 3d Old The Wagasa  Japanese Umbrella V.3
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type {GLTF} from 'three-stdlib'

class GLTFAction {
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material_0.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/old_the_wagasa__japanese_umbrella-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[2.915, 1.834, -0.015]} rotation={[0.022, -0.333, 0.014]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} position={[2.911, 1.382, 0.01]} rotation={[0.003, -0.225, -0.002]} scale={[0.04, 0.939, 0.042]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material_0.002']} position={[2.919, 0.049, 0]} />
    </group>
  )
}

useGLTF.preload('/models/old_the_wagasa__japanese_umbrella-transformed.glb')
