/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\samurai.glb -T --types 
Files: .\samurai.glb [80.17MB] > C:\Users\HP\Documents\projects\crimson-ronin\public\models\samurai-transformed.glb [2.95MB] (96%)
Author: Mikhail_Kozyrev (https://sketchfab.com/m_kozyrev)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/samurai-abada939487c4912b790bd28a5248b6e
Title: Samurai
*/

import * as THREE from 'three'
import React, {type JSX} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Floor_Floor_wire_177027088_0: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_11: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    Object_15: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_19: THREE.SkinnedMesh
    Object_21: THREE.SkinnedMesh
    Object_23: THREE.SkinnedMesh
    Object_25: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_29: THREE.SkinnedMesh
    Object_31: THREE.SkinnedMesh
    Object_33: THREE.SkinnedMesh
    Object_35: THREE.SkinnedMesh
    Object_37: THREE.SkinnedMesh
    Object_39: THREE.SkinnedMesh
    Object_67: THREE.SkinnedMesh
    Object_41: THREE.SkinnedMesh
    Object_43: THREE.SkinnedMesh
    Object_45: THREE.SkinnedMesh
    Object_47: THREE.SkinnedMesh
    Object_49: THREE.SkinnedMesh
    Object_51: THREE.SkinnedMesh
    Object_53: THREE.SkinnedMesh
    Object_55: THREE.SkinnedMesh
    Object_57: THREE.SkinnedMesh
    Object_59: THREE.SkinnedMesh
    Object_61: THREE.SkinnedMesh
    Object_63: THREE.SkinnedMesh
    Object_65: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Floor_wire_177027088: THREE.MeshStandardMaterial
    Material_424: THREE.MeshStandardMaterial
    Material_421: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/samurai-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  React.useEffect(() => {
    if (actions['Take 001']) {
      actions['Take 001'].play()
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_4">
          <group name="CATRigLLegDigit11Gizmo" position={[23.278, 2.947, -4.356]} rotation={[0, -1.257, 0]} scale={0.1} />
          <group name="CATRigRLegDigit11Gizmo" position={[-34.026, 2.962, 4.07]} rotation={[Math.PI, -0.669, -Math.PI]} scale={0.1} />
        </group>
        <primitive object={nodes._rootJoint} />
        <mesh name="Floor_Floor_wire_177027088_0" geometry={nodes.Floor_Floor_wire_177027088_0.geometry} material={materials.Floor_wire_177027088} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_424} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material_424} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material_424} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material_424} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material_424} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material_424} skeleton={nodes.Object_17.skeleton} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Material_424} skeleton={nodes.Object_19.skeleton} />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Material_424} skeleton={nodes.Object_21.skeleton} />
        <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Material_424} skeleton={nodes.Object_23.skeleton} />
        <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Material_424} skeleton={nodes.Object_25.skeleton} />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Material_424} skeleton={nodes.Object_27.skeleton} />
        <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Material_424} skeleton={nodes.Object_29.skeleton} />
        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Material_424} skeleton={nodes.Object_31.skeleton} />
        <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Material_424} skeleton={nodes.Object_33.skeleton} />
        <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Material_424} skeleton={nodes.Object_35.skeleton} />
        <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Material_424} skeleton={nodes.Object_37.skeleton} />
        <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Material_424} skeleton={nodes.Object_39.skeleton} />
        <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Material_424} skeleton={nodes.Object_67.skeleton} />
        <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Material_424} skeleton={nodes.Object_41.skeleton} />
        <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material_424} skeleton={nodes.Object_43.skeleton} />
        <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Material_424} skeleton={nodes.Object_45.skeleton} />
        <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Material_424} skeleton={nodes.Object_47.skeleton} />
        <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Material_424} skeleton={nodes.Object_49.skeleton} />
        <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Material_421} skeleton={nodes.Object_51.skeleton} />
        <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Material_424} skeleton={nodes.Object_53.skeleton} />
        <skinnedMesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Material_424} skeleton={nodes.Object_55.skeleton} />
        <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Material_424} skeleton={nodes.Object_57.skeleton} />
        <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Material_424} skeleton={nodes.Object_59.skeleton} />
        <skinnedMesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Material_424} skeleton={nodes.Object_61.skeleton} />
        <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Material_424} skeleton={nodes.Object_63.skeleton} />
        <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Material_424} skeleton={nodes.Object_65.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/samurai-transformed.glb')
